//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_game.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiddingHistory
    {
        public int Id { get; set; }
        public string GameName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
