//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_game.Models.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlinegame_AdminEntities : DbContext
    {
        public onlinegame_AdminEntities()
            : base("name=onlinegame_AdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddMoney> AddMoneys { get; set; }
        public virtual DbSet<AddResult> AddResults { get; set; }
        public virtual DbSet<BiddingHistory> BiddingHistorys { get; set; }
        public virtual DbSet<GameNumber> GameNumbers { get; set; }
        public virtual DbSet<GameRateList> GameRateLists { get; set; }
        public virtual DbSet<History> Historys { get; set; }
        public virtual DbSet<HowToPlay> HowToPlays { get; set; }
        public virtual DbSet<LoginMaster> LoginMasters { get; set; }
        public virtual DbSet<PlayHarup> PlayHarups { get; set; }
        public virtual DbSet<RefrenceReport> RefrenceReports { get; set; }
        public virtual DbSet<Reportwithdrawal> Reportwithdrawals { get; set; }
        public virtual DbSet<TermsAndCondition> TermsAndConditions { get; set; }
        public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }
        public virtual DbSet<WithdrawFund> WithdrawFunds { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameNumberHarup> GameNumberHarups { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<GameType> GameTypes { get; set; }
        public virtual DbSet<PlayJodi> PlayJodis { get; set; }
    }
}
