//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_game.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayHarup
    {
        public int Id { get; set; }
        public Nullable<int> Aside { get; set; }
        public Nullable<int> Bside { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
