//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_game.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefrenceReport
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> WinAmount { get; set; }
        public Nullable<decimal> AdminCommission { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastActivityOn { get; set; }
    }
}
